services:
  - type: web
    name: greenmove-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
